import xml.etree.ElementTree as ET

te_dict2 = {
    "ai_greeting": "నమస్కారం! నేను మీ ఏఐ వెల్నెస్ అసిస్టెంట్. మీ ఒత్తిడి ప్యాటర్న్స్ అర్థం చేసుకోవడంలో నేను సహాయపడగలను. మీరు ఏమి తెలుసుకోవాలనుకుంటున్నారు?",
    "ai_response": "మీ డేటా ఆధారంగా, మంగళవారాల్లో మీ ఒత్తిడి ఎక్కువగా ఉంటుంది. సోమవారాల్లో ఎక్కువ నిద్రపోవడానికి ప్రయత్నించండి.",
    "welcome_subtitle": "మీ ఏఐ ఆధారిత ఒత్తిడి పర్యవేక్షణ\nసహాయకుడు",
    "welcome_description": "మీ కార్టిసాల్ స్థాయిలను ట్రాక్ చేయండి, ప్యాటర్న్స్ విశ్లేషించండి మరియు ఒత్తిడిని సమర్థవంతంగా నిర్వహించడానికి వ్యక్తిగతీకరించిన సూచనలను పొందండి.",
    "complete_profile": "మీ ప్రొఫైల్ పూర్తి చేయండి",
    "personalize_experience": "మీ అనుభవాన్ని వ్యక్తిగతీకరించడానికి మాకు సహాయపడండి",
    "primary_goal_question": "మీ ప్రాథమిక లక్ష్యం ఏమిటి?",
    "complete_all_fields": "దయచేసి అన్ని వివరాలు పూర్తి చేయండి",
    "grant_permissions": "అనుమతులు ఇవ్వండి",
    "permissions_subtitle": "ఖచ్చితమైన ఒత్తిడి వివరాలు అందించడానికి మాకు కొన్ని అనుమతులు కావాలి",
    "activity_tracking": "కార్యాచరణ ట్రాకింగ్",
    "activity_tracking_desc": "ఒత్తిడి స్థాయిలను మెరుగ్గా అంచనా వేయడానికి మీ శారీరక కార్యాచరణ మరియు కదలికలను పర్యవేక్షించండి",
    "enable_tracking": "ట్రాకింగ్ ఆన్ చేయండి",
    "notifications_desc": "చెక్ ఇన్ చేయడానికి మరియు ఒత్తిడిని నిర్వహించడానికి సకాలంలో అలర్ట్స్ మరియు రిమైండర్‌లను పొందండి",
    "enable_notifications": "నోటిఫికేషన్లు ఆన్ చేయండి",
    "allow_access": "అనుమతించండి",
    "skip_for_now": "ప్రస్తుతానికి వదిలేయండి",
    "how_it_works_subtitle": "ఒత్తిడిని మెరుగ్గా నిర్వహించడానికి మూడు సులభమైన దశలు",
    "track_desc": "మీ రోజువారీ శారీరక, మానసిక మరియు జీవనశైలి డేటాను లాగ్ చేయండి",
    "analyze_desc": "కార్టిసాల్ స్థాయిలు మరియు ఒత్తిడి ప్రమాదాన్ని అంచనా వేయడానికి ఏఐ మీ ప్యాటర్న్స్ విశ్లేషిస్తుంది",
    "improve_desc": "ఒత్తిడిని తగ్గించడానికి మరియు బర్న్అవుట్ నివారించడానికి వ్యక్తిగతీకరించిన సూచనలను పొందండి",
    "signin_subtitle": "మీ వెల్నెస్ జర్నీ కొనసాగించడానికి సైన్ ఇన్ చేయండి",
    "email_placeholder": "john@example.com",
    "invalid_credentials": "తప్పు ఆధారాలు",
    "no_account": "ఖాతా లేదా? ",
    "signup_subtitle": "మీ ఒత్తిడి లేని ప్రయాణాన్ని ప్రారంభించడానికి కార్టిసెన్స్‌లో చేరండి",
    "fullname_placeholder": "జాన్ డో",
    "password_length_tip": "కనీసం 8 అక్షరాలు ఉండాలి",
    "all_fields_required": "అన్ని ఫీల్డ్స్ తప్పనిసరి",
    "invalid_email": "దయచేసి సరైన ఈమెయిల్ నమోదు చేయండి",
    "password_too_short": "పాస్వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి",
    "passwords_do_not_match": "పాస్వర్డ్లు సరిపోలడం లేదు",
    "reset_password_desc": "మీ ఈమెయిల్ నమోదు చేయండి, మీ పాస్వర్డ్ రీసెట్ చేయడానికి మేము ఒక లింక్ పంపుతాము",
    "back_to_signin": "సైన్ ఇన్ కు తిరిగి వెళ్ళండి",
    "checkin_subtitle": "మెరుగైన విశ్లేషణల కోసం మీ రోజును అర్థం చేసుకోవడంలో మాకు సహాయపడండి",
    "processing_markers": "శారీరక మార్కర్లను ప్రాసెస్ చేస్తోంది...",
    "analyzing_heart_rate": "హృదయ స్పందనలో మార్పులను విశ్లేషిస్తోంది",
    "evaluating_sleep": "నిద్ర ప్యాటర్న్స్ అంచనా వేస్తోంది",
    "computing_stress": "ఒత్తిడి సహసంబంధాలను లెక్కిస్తోంది",
    "generating_insights": "విశ్లేషణలు రూపొందిస్తోంది",
    "analyzing_data_desc": "ఒత్తిడి స్థాయిలను అంచనా వేయడానికి మా ఏఐ మీ డేటాను ప్రాసెస్ చేస్తోంది",
    "checkin_complete_title": "రోజువారీ చెక్-ఇన్ పూర్తయింది",
    "checkin_complete_desc": "చాలా బాగుంది! మీరు ఈరోజు చెక్-ఇన్ పూర్తి చేసారు.",
    "achievement_unlocked": "కొత్త లక్ష్యం చేరుకున్నారు",
    "streak_7day": "మీరు 7 రోజుల స్ట్రీక్ సాధించారు!",
    "weekly_improvement": "వారపు మెరుగుదల",
    "stress_drop_15": "ఈ వారం మీ ఒత్తిడి స్థాయిలు 15% తగ్గాయి.",
    "high_stress_detected": "అధిక ఒత్తిడి గుర్తింపు",
    "high_stress_desc": "మీ ఒత్తిడి స్థాయి ఎక్కువగా ఉంది. 5 నిమిషాలు విశ్రాంతి తీసుకోండి.",
    "normal_range": "సాధారణ స్థాయి",
    "legend": "వివరాలు",
    "profile_updated": "ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ చేయబడింది",
    "language_english": "English",
    "language_hindi": "हिन्दी (Hindi)",
    "language_telugu": "తెలుగు (Telugu)",
    "language_tamil": "தமிழ் (Tamil)",
    "language_french": "Français (French)",
    
    # Missing extracted keys
    "extracted_track_your_stress_pa": "కాలక్రమేణా మీ ఒత్తిడి ప్యాటర్న్స్ ట్రాక్ చేయండి",
    "extracted_recent_progress": "ఇటీవలి ప్రగతి",
    "extracted_current_week_summary": "ప్రస్తుత వారం సారాంశం",
    "extracted_updated_from_your_la": "మీ తాజా రికార్డుల నుండి అప్‌డేట్ చేయబడింది",
    "extracted_key_metrics": "ముఖ్యమైన కొలమానాలు",
    "extracted_breathing_exercise": "బ్రీతింగ్ వ్యాయామం",
    "extracted_5_min": "5 నిమిషాలు",
    "extracted_stay_updated_on_your": "మీ వెల్నెస్ జర్నీ పై అప్‌డేట్ గా ఉండండి",
    "extracted_monthly_report": "నెలవారీ రిపోర్ట్",
    "extracted_overview_of_all_your": "మీ మొత్తం డేటా యొక్క సంగ్రహం",
    "extracted_average_stress_score": "సగటు ఒత్తిడి స్కోరు",
    "extracted_stress_distribution": "ఒత్తిడి పంపిణీ",
    "extracted_monthly_achievement": "నెలవారీ విజయం",
    "extracted_factor_breakdown": "కారణాల విశ్లేషణ",
    "extracted_what_influences_your": "మీ ఒత్తిడి స్థాయిలను ఏవి ప్రభావితం చేస్తాయి",
    "extracted_contribution_analysi": "సహకారం విశ్లేషణ",
    "extracted_ai_recommendation": "ఏఐ సిఫార్సు",
    "extracted_your_past_daily_entr": "మీ గత రోజువారీ ఎంట్రీలు",
    "extracted_color_coded_stress_v": "రంగులతో కూడిన ఒత్తిడి విజువలైజేషన్",
    "extracted_current_month": "ప్రస్తుత నెల",
    "extracted_nutrition_tips": "పోషకాహార చిట్కాలు",
    "extracted_eat_to_reduce_stress": "ఒత్తిడి తగ్గించడానికి తినండి",
    "extracted_food_stress_connecti": "ఆహారం మరియు ఒత్తిడి సంబంధం",
    "extracted_what_you_eat_directl": "మీరు తినేది మీ ఒత్తిడి హార్మోన్లను నేరుగా ప్రభావితం చేస్తుంది.",
    "extracted_eat_stress_reducing_": "ఒత్తిడి తగ్గించే ఆహారాలు తినండి",
    "extracted_limit_caffeine_intak": "కెఫిన్ పరిమితం చేయండి",
    "extracted_mindfulness": "మైండ్‌ఫుల్‌నెస్",
    "extracted_guided_meditation": "గైడెడ్ మెడిటేషన్",
    "extracted_start_your_session": "మీ సెషన్ ప్రారంభించండి",
    "extracted_find_a_quiet_place_a": "ప్రశాంతమైన ప్రదేశాన్ని ఎంచుకోండి",
    "extracted_duration": "సమయం",
    "extracted_guided_sessions": "గైడెడ్ సెషన్స్",
    "extracted_morning_calm": "ఉదయం ప్రశాంతత",
    "extracted_5_min_guided": "5 నిమిషాలు • గైడెడ్",
    "extracted_great_job_today": "ఈరోజు చాలా బాగా చేసారు!",
    "extracted_you_ve_completed_you": "మీరు బ్రీతింగ్ వ్యాయామం పూర్తి చేసారు. ఇలాగే కొనసాగించండి!",
    "extracted_view_my_progress": "నా ప్రగతి చూడండి",
    "extracted_back_to_home": "హోమ్ కు తిరిగి వెళ్ళండి",
    "extracted_10_points_earned": "+10 పాయింట్లు వచ్చాయి",
    "extracted_ai_assistant": "ఏఐ అసిస్టెంట్",
    "extracted_type_a_message": "మెసేజ్ టైప్ చేయండి...",
    "extracted_history": "చరిత్ర",
    "extracted_score": "స్కోరు",
    "extracted_date": "తేదీ",
    "extracted_how_are_you_feeling_": "మీరు ఎలా ఉన్నారు?",
    "extracted_let_s_log_your_daily": "మీ రోజువారీ డేటాను లాగ్ చేద్దాం",
    "extracted_no_factors_logged": "ఏ కారణాలు లాగ్ చేయబడలేదు",
    "extracted_excellent_job_keep_m": "చాలా బాగుంది! ఇలాగే కొనసాగించండి.",
    "extracted_you_re_doing_well_bu": "మీరు బాగా చేస్తున్నారు, కానీ కొంచెం శ్రద్ధ వహించండి.",
    "extracted_high_stress_detected": "అధిక ఒత్తిడి! దయచేసి విశ్రాంతి తీసుకోండి.",
    "extracted_ai_analysis": "ఏఐ విశ్లేషణ",
    "extracted_your_cortisol_indica": "మీ కార్టిసాల్ సూచికలు:",
    "extracted_you_haven_t_logged_a": "మీరు ఇంకా ఏ డేటాను లాగ్ చేయలేదు.",
    "extracted_check_in_now": "ఇప్పుడే చెక్-ఇన్ చేయండి"
}

tree = ET.parse('app/src/main/res/values-te/strings.xml')
root = tree.getroot()

for child in root:
    if 'name' in child.attrib:
        key = child.attrib['name']
        if key in te_dict2:
            child.text = te_dict2[key]
            
xml_str = ET.tostring(root, encoding='utf-8', xml_declaration=True).decode('utf-8')
with open('app/src/main/res/values-te/strings.xml', 'w', encoding='utf-8') as f:
    f.write(xml_str.replace('><', '>\n    <').replace('</resources>', '\n</resources>'))

print("Telugu Phase 2 applied.")
