import json
import xml.etree.ElementTree as ET

ta_dict = {
    "app_name": "கார்டிசென்ஸ்",
    "welcome": "கார்டிசென்ஸுக்கு வரவேற்கிறோம்",
    "get_started": "தொடங்குங்கள்",
    "sign_in": "உள்நுழைக",
    "good_morning": "காலை வணக்கம்,",
    "stress_score": "மன அழுத்த மதிப்பெண்",
    "home": "முகப்பு",
    "analytics": "பகுப்பாய்வு",
    "checkin": "செக்-இன்",
    "ai_chat": "ஏஐ அரட்டை",
    "profile": "சுயவிவரம்",
    "settings": "அமைப்புகள்",
    "language": "மொழி",
    "dark_mode": "டார்க் மோட்",
    "logout": "வெளியேறு",
    "analyzing": "பகுப்பாய்வு செய்கிறது",
    "results_title": "முடிவுகள்",
    "main_reasons": "முக்கிய காரணங்கள்:",
    "view_insights": "விவரங்களைக் காண்க",
    "recheck": "மீண்டும் சரிபார்க்கவும்",
    "ai_greeting": "வணக்கம்! நான் உங்கள் ஏஐ உதவியாளர். உங்கள் மன அழுத்த முறைகளைப் புரிந்துகொள்ள நான் உங்களுக்கு உதவ முடியும்.",
    "ai_response": "உங்கள் தரவின்படி, செவ்வாய்க்கிழமைகளில் உங்கள் மன அழுத்தம் அதிகமாக இருக்கும்.",
    "tagline": "மன அழுத்தத்தை கணிக்கவும். தடுக்கவும்.",
    "welcome_subtitle": "உங்கள் ஏஐ மன அழுத்த கண்காணிப்பு தோழன்",
    "welcome_description": "உங்கள் கார்டிசோல் அளவைக் கண்காணிக்கவும், வடிவங்களை பகுப்பாய்வு செய்யவும்.",
    "complete_profile": "சுயவிவரத்தை முடிக்கவும்",
    "personalize_experience": "உங்கள் அனுபவத்தை தனிப்பயனாக்க எங்களுக்கு உதவுங்கள்",
    "age": "வயது",
    "enter_age": "வயதை உள்ளிடவும்",
    "gender": "பாலினம்",
    "select_gender": "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
    "primary_goal_question": "உங்கள் முதன்மை இலக்கு என்ன?",
    "reduce_stress": "மன அழுத்தத்தைக் குறைக்கவும்",
    "better_sleep": "சிறந்த தூக்கம்",
    "improve_focus": "கவனத்தை மேம்படுத்தவும்",
    "complete_all_fields": "தயவுசெய்து அனைத்து புலங்களையும் நிரப்பவும்",
    "continue_btn": "தொடரவும்",
    "grant_permissions": "அனுமதிகளை வழங்கவும்",
    "permissions_subtitle": "சரியான நுண்ணறிவுகளை வழங்க எங்களுக்கு சில அனுமதிகள் தேவை",
    "activity_tracking": "செயல்பாட்டு கண்காணிப்பு",
    "activity_tracking_desc": "மன அழுத்த அளவைக் கணிக்க உடல் செயல்பாடுகளைக் கண்காணிக்கவும்",
    "enable_tracking": "கண்காணிப்பை இயக்கவும்",
    "notifications": "அறிவிப்புகள்",
    "notifications_desc": "செக்-இன் செய்ய நினைவூட்டல்களைப் பெறவும்",
    "enable_notifications": "அறிவிப்புகளை இயக்கவும்",
    "allow_access": "அனுமதிக்கவும்",
    "skip_for_now": "இப்போதைக்கு தவிர்க்கவும்",
    "how_it_works": "இது எப்படி வேலை செய்கிறது",
    "how_it_works_subtitle": "சிறந்த மன அழுத்த மேலாண்மைக்கான மூன்று எளிய படிகள்",
    "track": "1. கண்காணிக்கவும்",
    "track_desc": "உங்கள் தினசரி தரவை பதிவு செய்யவும்",
    "analyze": "2. பகுப்பாய்வு செய்யவும்",
    "analyze_desc": "ஏஐ மன அழுத்த அபாயத்தை பகுப்பாய்வு செய்கிறது",
    "improve": "3. மேம்படுத்தவும்",
    "improve_desc": "தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெறவும்",
    "welcome_back": "மீண்டும் வருக",
    "signin_subtitle": "உங்கள் பயணத்தைத் தொடர உள்நுழைக",
    "email_address": "மின்னஞ்சல்",
    "email_placeholder": "john@example.com",
    "password": "கடவுச்சொல்",
    "forgot_password": "கடவுச்சொல் மறந்துவிட்டதா?",
    "invalid_credentials": "தவறான சான்றுகள்",
    "no_account": "கணக்கு இல்லையா? ",
    "signup": "பதிவு செய்க",
    "create_account": "கணக்கை உருவாக்கவும்",
    "signup_subtitle": "உங்கள் மன அழுத்தம் இல்லாத பயணத்தைத் தொடங்க கார்டிசென்ஸில் சேரவும்",
    "full_name": "முழு பெயர்",
    "fullname_placeholder": "ஜான் டோ",
    "confirm_password": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "password_length_tip": "குறைந்தபட்சம் 8 எழுத்துக்கள் இருக்க வேண்டும்",
    "all_fields_required": "அனைத்து புலங்களும் கட்டாயம்",
    "invalid_email": "சரியான மின்னஞ்சலை உள்ளிடவும்",
    "password_too_short": "கடவுச்சொல் குறைந்தபட்சம் 8 எழுத்துக்கள் இருக்க வேண்டும்",
    "passwords_do_not_match": "கடவுச்சொற்கள் பொருந்தவில்லை",
    "reset_password": "கடவுச்சொல்லை மீட்டமைக்கவும்",
    "reset_password_desc": "உங்கள் மின்னஞ்சலை உள்ளிடவும், நாங்கள் ஒரு இணைப்பை அனுப்புவோம்",
    "send_reset_link": "மீட்டமைப்பு இணைப்பை அனுப்பு",
    "back_to_signin": "உள்நுழைவுக்குத் திரும்பு",
    "daily_checkin": "தினசரி செக்-இன்",
    "checkin_subtitle": "சிறந்த நுண்ணறிவுகளுக்கு உங்கள் நாளைப் புரிந்துகொள்ள உதவுங்கள்",
    "analyze_stress": "மன அழுத்தத்தை பகுப்பாய்வு செய்",
    "processing_markers": "தரவு செயலாக்கப்படுகிறது...",
    "analyzing_heart_rate": "இதயத் துடிப்பை பகுப்பாய்வு செய்கிறது",
    "evaluating_sleep": "தூக்கத்தை மதிப்பிடுகிறது",
    "computing_stress": "மன அழுத்தத்தை கணக்கிடுகிறது",
    "generating_insights": "நுண்ணறிவுகளை உருவாக்குகிறது",
    "analyzing_data_desc": "மன அழுத்தத்தை மதிப்பிட எங்கள் ஏஐ உங்கள் தரவை செயலாக்குகிறது",
    "checkin_complete_title": "செக்-இன் முடிந்தது",
    "checkin_complete_desc": "மிக நன்று! நீங்கள் இன்றைய செக்-இன்னை முடித்துவிட்டீர்கள்.",
    "achievement_unlocked": "சாதனை திறக்கப்பட்டது",
    "streak_7day": "நீங்கள் 7 நாள் தொடரை முடித்துள்ளீர்கள்!",
    "weekly_improvement": "வாராந்திர மேம்பாடு",
    "stress_drop_15": "இந்த வாரம் உங்கள் மன அழுத்த அளவுகள் 15% குறைந்துள்ளன.",
    "high_stress_detected": "அதிக மன அழுத்தம் கண்டறியப்பட்டது",
    "high_stress_desc": "உங்கள் மன அழுத்தம் அதிகமாக உள்ளது. 5 நிமிடம் ஓய்வெடுக்கவும்.",
    "avg_this_week": "இந்த வாரம் சராசரி",
    "streak": "தொடர்",
    "weekly_trend": "வாராந்திர போக்கு",
    "last_7_days": "கடந்த 7 நாட்கள்",
    "low": "குறைவு",
    "moderate": "மிதமான",
    "high": "அதிகம்",
    "stress_trends": "மன அழுத்த போக்குகள்",
    "overall_trend": "ஒட்டுமொத்த போக்கு",
    "improving": "மேம்படுகிறது",
    "current_avg": "தற்போதைய சராசரி",
    "monthly_progress": "மாதாந்திர முன்னேற்றம்",
    "key_insight": "முக்கிய நுண்ணறிவு",
    "weekly_report": "வாராந்திர அறிக்கை",
    "avg_heart_rate": "சராசரி இதயத் துடிப்பு",
    "avg_sleep": "சராசரி தூக்கம்",
    "energy_level": "ஆற்றல் நிலை",
    "best_day": "சிறந்த நாள்",
    "excellent": "சிறப்பானது",
    "normal_range": "சாதாரண வரம்பு",
    "history_log": "வரலாறு",
    "stress_calendar": "நாள்காட்டி",
    "legend": "விவரம்",
    "edit_profile": "சுயவிவரத்தை திருத்து",
    "save_profile": "சேமிக்க",
    "profile_updated": "சுயவிவரம் புதுப்பிக்கப்பட்டது",
    "name_label": "பெயர்",
    "language_english": "English",
    "language_hindi": "हिन्दी (Hindi)",
    "language_telugu": "తెలుగు (Telugu)",
    "language_tamil": "தமிழ் (Tamil)",
    "language_french": "Français (French)",
    "chat_error": "இணைப்பதில் சிக்கல். மீண்டும் முயற்சிக்கவும்.",
    "chat_stress_reply": "உங்கள் பகுப்பாய்வின்படி, உங்கள் மன அழுத்தம் %1$s.",
    "chat_stress_high": "சில சுவாசப் பயிற்சிகளைப் பரிந்துரைக்கிறேன்.",
    "chat_stress_low": "நீங்கள் மிக நன்றாக செய்கிறீர்கள்!",
    "chat_sleep_reply": "உங்கள் சராசரி தூக்கம் %1$s. சிறந்த ஆரோக்கியத்திற்கு 7-9 மணி நேரம் தூங்கவும்.",
    "chat_hello": "வணக்கம்! நான் உங்கள் கார்டிசென்ஸ் ஏஐ. நான் எப்படி உதவ முடியும்?",
    "chat_default": "எனக்குப் புரிகிறது. உங்கள் போக்குகளைக் காண விரும்புகிறீர்களா?",
    "extracted_overview": "கண்ணோட்டம்",
    "extracted_trends": "போக்குகள்",
    "extracted_report": "அறிக்கை",
    "extracted_monthly": "மாதாந்திர",
    "extracted_view_all": "அனைத்தையும் காண்க",
    "extracted_heart_rate": "இதயத் துடிப்பு",
    "extracted_sleep": "தூக்கம்",
    "extracted_recent_check_ins": "சமீபத்திய செக்-இன்கள்",
    "extracted_bpm": "பிபிஎம்",
    "extracted_hrs": "மணிநேரம்",
    "extracted_ask_me_anything": "என்னை எதையும் கேளுங்கள்",
    "extracted_ask_about_your_stres": "உங்கள் மன அழுத்தத்தைப் பற்றி கேளுங்கள்...",
    "extracted_cortisense": "கார்டிசென்ஸ்",
    "extracted_how_is_your_mood_rig": "உங்கள் மனநிலை இப்போது எப்படி இருக்கிறது?",
    "extracted_are_you_feeling_anxi": "நீங்கள் கவலையாக உணர்கிறீர்களா?",
    "extracted_how_many_hours_did_y": "நீங்கள் எத்தனை மணி நேரம் தூங்கினீர்கள்?",
    "extracted_how_much_caffeine_to": "இன்று எவ்வளவு காஃபின் குடித்தீர்கள்?",
    "extracted_screen_usage_today_": "இன்று திரை பயன்பாடு?",
    "extracted_how_busy_was_your_da": "இன்று நீங்கள் எவ்வளவு பிஸியாக இருந்தீர்கள்?",
    "extracted_how_does_your_body_f": "உங்கள் உடல் எப்படி உணர்கிறது?",
    "extracted_good": "நன்று",
    "extracted_okay": "பரவாயில்லை",
    "extracted_bad": "மோசம்",
    "extracted_very_fast": "மிகவும் வேகம்",
    "extracted_calm": "அமைதி",
    "extracted_fast": "வேகம்",
    "extracted_change_photo": "புகைப்படத்தை மாற்று",
    "extracted_select_language": "மொழியைத் தேர்ந்தெடுக்கவும்",
    "extracted_cancel": "ரத்துசெய்",
    "extracted_track_your_stress_pa": "உங்கள் மன அழுத்தப் போக்குகளைக் கண்காணிக்கவும்",
    "extracted_recent_progress": "சமீபத்திய முன்னேற்றம்",
    "extracted_current_week_summary": "இந்த வார சுருக்கம்",
    "extracted_updated_from_your_la": "சமீபத்திய பதிவுகளிலிருந்து புதுப்பிக்கப்பட்டது",
    "extracted_key_metrics": "முக்கிய அளவீடுகள்",
    "extracted_breathing_exercise": "சுவாசப் பயிற்சி",
    "extracted_5_min": "5 நிமிடம்",
    "extracted_stay_updated_on_your": "உங்கள் பயணத்தில் புதுப்பித்த நிலையில் இருங்கள்",
    "extracted_monthly_report": "மாதாந்திர அறிக்கை",
    "extracted_overview_of_all_your": "உங்கள் எல்லா தரவுகளின் கண்ணோட்டம்",
    "extracted_average_stress_score": "சராசரி மன அழுத்த மதிப்பெண்",
    "extracted_stress_distribution": "மன அழுத்த விநியோகம்",
    "extracted_monthly_achievement": "மாதாந்திர சாதனை",
    "extracted_factor_breakdown": "காரணி முறிவு",
    "extracted_what_influences_your": "மன அழுத்தத்தை எது பாதிக்கிறது",
    "extracted_contribution_analysi": "பங்களிப்பு பகுப்பாய்வு",
    "extracted_ai_recommendation": "ஏஐ பரிந்துரை",
    "extracted_your_past_daily_entr": "உங்கள் கடந்தகால பதிவுகள்",
    "extracted_color_coded_stress_v": "வண்ணக் குறியீட்டு மன அழுத்த காட்சி",
    "extracted_current_month": "தற்போதைய மாதம்",
    "extracted_nutrition_tips": "ஊட்டச்சத்து குறிப்புகள்",
    "extracted_eat_to_reduce_stress": "மன அழுத்தத்தைக் குறைக்க சாப்பிடுங்கள்",
    "extracted_food_stress_connecti": "உணவு மற்றும் மன அழுத்த இணைப்பு",
    "extracted_what_you_eat_directl": "நீங்கள் சாப்பிடுவது உங்கள் மன அழுத்தத்தை நேரடியாக பாதிக்கிறது.",
    "extracted_eat_stress_reducing_": "மன அழுத்தத்தைக் குறைக்கும் உணவுகளை உண்ணுங்கள்",
    "extracted_limit_caffeine_intak": "காஃபினை கட்டுப்படுத்துங்கள்",
    "extracted_mindfulness": "நினைவாற்றல்",
    "extracted_guided_meditation": "வழிகாட்டப்பட்ட தியானம்",
    "extracted_start_your_session": "உங்கள் அமர்வைத் தொடங்கவும்",
    "extracted_find_a_quiet_place_a": "அமைதியான இடத்தைக் கண்டுபிடி",
    "extracted_duration": "காலம்",
    "extracted_guided_sessions": "வழிகாட்டப்பட்ட அமர்வுகள்",
    "extracted_morning_calm": "காலை அமைதி",
    "extracted_5_min_guided": "5 நிமிடம் • வழிகாட்டப்பட்டது",
    "extracted_great_job_today": "இன்று சிறந்த வேலை!",
    "extracted_you_ve_completed_you": "உங்கள் சுவாசப் பயிற்சியை முடித்துவிட்டீர்கள்.",
    "extracted_view_my_progress": "என் முன்னேற்றத்தைக் காண்க",
    "extracted_back_to_home": "முகப்புக்குத் திரும்பு",
    "extracted_10_points_earned": "+10 புள்ளிகள்",
    "extracted_ai_assistant": "ஏஐ உதவியாளர்",
    "extracted_type_a_message": "செய்தியை தட்டச்சு செய்க...",
    "extracted_history": "வரலாறு",
    "extracted_score": "மதிப்பெண்",
    "extracted_date": "தேதி",
    "extracted_how_are_you_feeling_": "நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "extracted_let_s_log_your_daily": "உங்கள் தினசரி தரவை பதிவு செய்வோம்",
    "extracted_no_factors_logged": "எந்த காரணிகளும் இல்லை",
    "extracted_excellent_job_keep_m": "சிறந்த வேலை! தொடரவும்.",
    "extracted_you_re_doing_well_bu": "நீங்கள் நன்றாக செய்கிறீர்கள், ஆனால் கவனமாக இருங்கள்.",
    "extracted_high_stress_detected": "அதிக மன அழுத்தம்! தயவுசெய்து ஓய்வெடுங்கள்.",
    "extracted_ai_analysis": "ஏஐ பகுப்பாய்வு",
    "extracted_your_cortisol_indica": "உங்கள் கார்டிசோல் குறிகாட்டிகள்:",
    "extracted_you_haven_t_logged_a": "நீங்கள் இன்னும் எந்த தரவையும் பதிவு செய்யவில்லை.",
    "extracted_check_in_now": "இப்போது செக்-இன் செய்"
}

tree = ET.parse('app/src/main/res/values-ta/strings.xml')
root = tree.getroot()

for child in root:
    if 'name' in child.attrib:
        key = child.attrib['name']
        if key in ta_dict:
            child.text = ta_dict[key]
            
xml_str = ET.tostring(root, encoding='utf-8', xml_declaration=True).decode('utf-8')
with open('app/src/main/res/values-ta/strings.xml', 'w', encoding='utf-8') as f:
    f.write(xml_str.replace('><', '>\n    <').replace('</resources>', '\n</resources>'))

print("Tamil translations applied.")
