import json
import xml.etree.ElementTree as ET

fr_dict = {
    "app_name": "CortiSense",
    "welcome": "Bienvenue sur\nCortiSense",
    "get_started": "Commencer",
    "sign_in": "Se connecter",
    "good_morning": "Bonjour,",
    "stress_score": "Score de stress",
    "home": "Accueil",
    "analytics": "Analytique",
    "checkin": "Check-in",
    "ai_chat": "Chat IA",
    "profile": "Profil",
    "settings": "Paramètres",
    "language": "Langue",
    "dark_mode": "Mode Sombre",
    "logout": "Se déconnecter",
    "analyzing": "Analyse en cours",
    "results_title": "Résultats",
    "main_reasons": "Raisons principales:",
    "view_insights": "Voir les détails",
    "recheck": "Revérifier",
    "ai_greeting": "Bonjour! Je suis votre assistant IA. Comment puis-je vous aider?",
    "ai_response": "D'après vos données, votre stress est plus élevé le mardi.",
    "tagline": "Prédire le stress. Prévenir l'épuisement.",
    "welcome_subtitle": "Votre compagnon IA de gestion du stress",
    "welcome_description": "Suivez vos niveaux de cortisol, analysez vos modèles et obtenez des recommandations personnalisées.",
    "complete_profile": "Complétez votre profil",
    "personalize_experience": "Aidez-nous à personnaliser votre expérience",
    "age": "Âge",
    "enter_age": "Entrez votre âge",
    "gender": "Genre",
    "select_gender": "Sélectionnez votre genre",
    "primary_goal_question": "Quel est votre objectif principal?",
    "reduce_stress": "Réduire le stress",
    "better_sleep": "Mieux dormir",
    "improve_focus": "Améliorer la concentration",
    "complete_all_fields": "Veuillez remplir tous les champs",
    "continue_btn": "Continuer",
    "grant_permissions": "Accorder les autorisations",
    "permissions_subtitle": "Nous avons besoin de certaines autorisations pour fournir des informations précises",
    "activity_tracking": "Suivi d'activité",
    "activity_tracking_desc": "Surveiller votre activité physique pour mieux prédire le stress",
    "enable_tracking": "Activer le suivi",
    "notifications": "Notifications",
    "notifications_desc": "Recevez des alertes pour effectuer un check-in et gérer votre stress",
    "enable_notifications": "Activer les notifications",
    "allow_access": "Autoriser l'accès",
    "skip_for_now": "Ignorer pour le moment",
    "how_it_works": "Comment ça marche",
    "how_it_works_subtitle": "Trois étapes simples pour mieux gérer le stress",
    "track": "1. Suivre",
    "track_desc": "Enregistrez vos données quotidiennes",
    "analyze": "2. Analyser",
    "analyze_desc": "L'IA analyse vos habitudes de stress",
    "improve": "3. Améliorer",
    "improve_desc": "Obtenez des conseils personnalisés pour réduire le stress",
    "welcome_back": "De retour",
    "signin_subtitle": "Connectez-vous pour continuer votre parcours",
    "email_address": "Adresse e-mail",
    "email_placeholder": "john@example.com",
    "password": "Mot de passe",
    "forgot_password": "Mot de passe oublié?",
    "invalid_credentials": "Identifiants invalides",
    "no_account": "Pas de compte? ",
    "signup": "S'inscrire",
    "create_account": "Créer un compte",
    "signup_subtitle": "Rejoignez CortiSense pour commencer votre parcours sans stress",
    "full_name": "Nom complet",
    "fullname_placeholder": "John Doe",
    "confirm_password": "Confirmer le mot de passe",
    "password_length_tip": "Au moins 8 caractères",
    "all_fields_required": "Tous les champs sont requis",
    "invalid_email": "Veuillez entrer une adresse e-mail valide",
    "password_too_short": "Le mot de passe doit contenir au moins 8 caractères",
    "passwords_do_not_match": "Les mots de passe ne correspondent pas",
    "reset_password": "Réinitialiser le mot de passe",
    "reset_password_desc": "Entrez votre adresse e-mail et nous vous enverrons un lien",
    "send_reset_link": "Envoyer le lien",
    "back_to_signin": "Retour à la connexion",
    "daily_checkin": "Check-in Quotidien",
    "checkin_subtitle": "Aidez-nous à comprendre votre journée",
    "analyze_stress": "Analyser le stress",
    "processing_markers": "Traitement des données...",
    "analyzing_heart_rate": "Analyse de la fréquence cardiaque",
    "evaluating_sleep": "Évaluation du sommeil",
    "computing_stress": "Calcul des corrélations de stress",
    "generating_insights": "Génération des résultats",
    "analyzing_data_desc": "Notre IA traite vos données pour évaluer votre stress",
    "checkin_complete_title": "Check-in terminé",
    "checkin_complete_desc": "Excellent! Vous avez terminé votre check-in aujourd'hui.",
    "achievement_unlocked": "Succès débloqué",
    "streak_7day": "Vous avez atteint une série de 7 jours!",
    "weekly_improvement": "Amélioration hebdomadaire",
    "stress_drop_15": "Votre niveau de stress a diminué de 15% cette semaine.",
    "high_stress_detected": "Stress élevé détecté",
    "high_stress_desc": "Votre stress est élevé. Prenez 5 minutes pour vous détendre.",
    "avg_this_week": "Moyenne cette semaine",
    "streak": "Série",
    "weekly_trend": "Tendance hebdomadaire",
    "last_7_days": "7 derniers jours",
    "low": "Faible",
    "moderate": "Modéré",
    "high": "Élevé",
    "stress_trends": "Tendances de stress",
    "overall_trend": "Tendance globale",
    "improving": "En amélioration",
    "current_avg": "Moyenne actuelle",
    "monthly_progress": "Progrès mensuel",
    "key_insight": "Aperçu clé",
    "weekly_report": "Rapport hebdomadaire",
    "avg_heart_rate": "Rythme cardiaque moyen",
    "avg_sleep": "Sommeil moyen",
    "energy_level": "Niveau d'énergie",
    "best_day": "Meilleur jour",
    "excellent": "Excellent",
    "normal_range": "Plage normale",
    "history_log": "Historique",
    "stress_calendar": "Calendrier de stress",
    "legend": "Légende",
    "edit_profile": "Modifier le profil",
    "save_profile": "Enregistrer le profil",
    "profile_updated": "Profil mis à jour avec succès",
    "name_label": "Nom",
    "language_english": "English",
    "language_hindi": "हिन्दी (Hindi)",
    "language_telugu": "తెలుగు (Telugu)",
    "language_tamil": "தமிழ் (Tamil)",
    "language_french": "Français (French)",
    "chat_error": "Problème de connexion. Veuillez réessayer.",
    "chat_stress_reply": "Selon votre dernière analyse, votre stress est %1$s.",
    "chat_stress_high": "Je vous suggère des exercices de respiration.",
    "chat_stress_low": "Vous vous en sortez très bien!",
    "chat_sleep_reply": "Votre sommeil moyen est de %1$s. Visez 7 à 9 heures.",
    "chat_hello": "Bonjour! Je suis l'assistant IA de CortiSense. Comment puis-je vous aider?",
    "chat_default": "Je comprends. La gestion du stress est importante.",
    "extracted_overview": "Aperçu",
    "extracted_trends": "Tendances",
    "extracted_report": "Rapport",
    "extracted_monthly": "Mensuel",
    "extracted_view_all": "Voir tout",
    "extracted_heart_rate": "Fréquence cardiaque",
    "extracted_sleep": "Sommeil",
    "extracted_recent_check_ins": "Check-ins récents",
    "extracted_bpm": "bpm",
    "extracted_hrs": "heures",
    "extracted_ask_me_anything": "Demandez-moi n'importe quoi",
    "extracted_ask_about_your_stres": "Renseignez-vous sur votre stress...",
    "extracted_cortisense": "CortiSense",
    "extracted_how_is_your_mood_rig": "Comment est votre humeur?",
    "extracted_are_you_feeling_anxi": "Vous sentez-vous anxieux?",
    "extracted_how_many_hours_did_y": "Combien d'heures avez-vous dormi?",
    "extracted_how_much_caffeine_to": "Combien de caféine aujourd'hui?",
    "extracted_screen_usage_today_": "Utilisation des écrans aujourd'hui?",
    "extracted_how_busy_was_your_da": "À quel point votre journée était-elle occupée?",
    "extracted_how_does_your_body_f": "Comment se sent votre corps?",
    "extracted_good": "Bien",
    "extracted_okay": "Moyen",
    "extracted_bad": "Mal",
    "extracted_very_fast": "Très rapide",
    "extracted_calm": "Calme",
    "extracted_fast": "Rapide",
    "extracted_change_photo": "Changer la photo",
    "extracted_select_language": "Sélectionner la langue",
    "extracted_cancel": "Annuler",
    "extracted_track_your_stress_pa": "Suivez vos tendances de stress",
    "extracted_recent_progress": "Progrès récents",
    "extracted_current_week_summary": "Résumé de cette semaine",
    "extracted_updated_from_your_la": "Mis à jour à partir de vos derniers enregistrements",
    "extracted_key_metrics": "Indicateurs clés",
    "extracted_breathing_exercise": "Exercice de respiration",
    "extracted_5_min": "5 min",
    "extracted_stay_updated_on_your": "Restez informé sur votre santé",
    "extracted_monthly_report": "Rapport mensuel",
    "extracted_overview_of_all_your": "Aperçu de toutes vos données",
    "extracted_average_stress_score": "Score de stress moyen",
    "extracted_stress_distribution": "Répartition du stress",
    "extracted_monthly_achievement": "Réalisation mensuelle",
    "extracted_factor_breakdown": "Répartition des facteurs",
    "extracted_what_influences_your": "Qu'est-ce qui influence votre stress",
    "extracted_contribution_analysi": "Analyse de contribution",
    "extracted_ai_recommendation": "Recommandation de l'IA",
    "extracted_your_past_daily_entr": "Vos entrées quotidiennes passées",
    "extracted_color_coded_stress_v": "Visualisation du stress par code couleur",
    "extracted_current_month": "Mois actuel",
    "extracted_nutrition_tips": "Conseils en nutrition",
    "extracted_eat_to_reduce_stress": "Mangez pour réduire le stress",
    "extracted_food_stress_connecti": "Lien entre alimentation et stress",
    "extracted_what_you_eat_directl": "Ce que vous mangez affecte directement votre stress.",
    "extracted_eat_stress_reducing_": "Mangez des aliments anti-stress",
    "extracted_limit_caffeine_intak": "Limitez la caféine",
    "extracted_mindfulness": "Pleine conscience",
    "extracted_guided_meditation": "Méditation guidée",
    "extracted_start_your_session": "Commencez votre session",
    "extracted_find_a_quiet_place_a": "Trouvez un endroit calme et détendez-vous",
    "extracted_duration": "Durée",
    "extracted_guided_sessions": "Sessions guidées",
    "extracted_morning_calm": "Calme matinal",
    "extracted_5_min_guided": "5 min • Guidé",
    "extracted_great_job_today": "Excellent travail aujourd'hui!",
    "extracted_you_ve_completed_you": "Vous avez terminé votre exercice de respiration.",
    "extracted_view_my_progress": "Voir mes progrès",
    "extracted_back_to_home": "Retour à l'accueil",
    "extracted_10_points_earned": "+10 points gagnés",
    "extracted_ai_assistant": "Assistant IA",
    "extracted_type_a_message": "Tapez un message...",
    "extracted_history": "Historique",
    "extracted_score": "Score",
    "extracted_date": "Date",
    "extracted_how_are_you_feeling_": "Comment vous sentez-vous?",
    "extracted_let_s_log_your_daily": "Enregistrons vos données",
    "extracted_no_factors_logged": "Aucun facteur enregistré",
    "extracted_excellent_job_keep_m": "Excellent! Continuez ainsi.",
    "extracted_you_re_doing_well_bu": "Vous vous en sortez bien, mais faites attention.",
    "extracted_high_stress_detected": "Stress élevé! Prenez le temps de vous détendre.",
    "extracted_ai_analysis": "Analyse de l'IA",
    "extracted_your_cortisol_indica": "Vos indicateurs de cortisol:",
    "extracted_you_haven_t_logged_a": "Vous n'avez encore rien enregistré.",
    "extracted_check_in_now": "Check-in maintenant"
}

tree = ET.parse('app/src/main/res/values-fr/strings.xml')
root = tree.getroot()

for child in root:
    if 'name' in child.attrib:
        key = child.attrib['name']
        if key in fr_dict:
            child.text = fr_dict[key]
            
xml_str = ET.tostring(root, encoding='utf-8', xml_declaration=True).decode('utf-8')
with open('app/src/main/res/values-fr/strings.xml', 'w', encoding='utf-8') as f:
    f.write(xml_str.replace('><', '>\n    <').replace('</resources>', '\n</resources>'))

print("French translations applied.")