import json
import xml.etree.ElementTree as ET

hi_dict = {
    "app_name": "कॉर्टीसेंस",
    "welcome": "कॉर्टीसेंस में आपका स्वागत है",
    "get_started": "शुरू करें",
    "sign_in": "साइन इन",
    "good_morning": "सुप्रभात,",
    "stress_score": "तनाव स्कोर",
    "home": "होम",
    "analytics": "एनालिटिक्स",
    "checkin": "चेक-इन",
    "ai_chat": "एआई चैट",
    "profile": "प्रोफ़ाइल",
    "settings": "सेटिंग्स",
    "language": "भाषा",
    "dark_mode": "डार्क मोड",
    "logout": "लॉग आउट",
    "analyzing": "विश्लेषण हो रहा है",
    "results_title": "परिणाम",
    "main_reasons": "मुख्य कारण:",
    "view_insights": "विस्तृत जानकारी देखें",
    "recheck": "फिर से जाँच करें",
    "ai_greeting": "नमस्ते! मैं आपका एआई वेलनेस असिस्टेंट हूं। मैं आपके तनाव पैटर्न को समझने में मदद कर सकता हूं।",
    "ai_response": "आपके डेटा के आधार पर, आपका तनाव मंगलवार को सबसे अधिक होता है।",
    "tagline": "तनाव का अनुमान लगाएं। बर्नआउट को रोकें।",
    "welcome_subtitle": "आपका एआई तनाव मॉनिटरिंग साथी",
    "welcome_description": "तनाव को कम करने के लिए अपने कोर्टिसोल स्तरों को ट्रैक करें और विश्लेषण करें।",
    "complete_profile": "अपनी प्रोफ़ाइल पूरी करें",
    "personalize_experience": "अपने अनुभव को बेहतर बनाने में हमारी मदद करें",
    "age": "उम्र",
    "enter_age": "उम्र दर्ज करें",
    "gender": "लिंग",
    "select_gender": "लिंग चुनें",
    "primary_goal_question": "आपका मुख्य लक्ष्य क्या है?",
    "reduce_stress": "तनाव कम करें",
    "better_sleep": "बेहतर नींद",
    "improve_focus": "ध्यान बढ़ाएं",
    "complete_all_fields": "कृपया सभी फ़ील्ड भरें",
    "continue_btn": "जारी रखें",
    "grant_permissions": "अनुमतियां दें",
    "permissions_subtitle": "सटीक जानकारी के लिए कुछ अनुमतियां चाहिए",
    "activity_tracking": "एक्टिविटी ट्रैकिंग",
    "activity_tracking_desc": "तनाव के स्तर का बेहतर अनुमान लगाने के लिए मूवमेंट ट्रैक करें",
    "enable_tracking": "ट्रैकिंग सक्षम करें",
    "notifications": "सूचनाएं",
    "notifications_desc": "चेक-इन और तनाव प्रबंधन के लिए रिमाइंडर प्राप्त करें",
    "enable_notifications": "सूचनाएं सक्षम करें",
    "allow_access": "अनुमति दें",
    "skip_for_now": "अभी के लिए छोड़ें",
    "how_it_works": "यह कैसे काम करता है",
    "how_it_works_subtitle": "तनाव प्रबंधन के तीन सरल चरण",
    "track": "1. ट्रैक करें",
    "track_desc": "अपना दैनिक डेटा दर्ज करें",
    "analyze": "2. विश्लेषण करें",
    "analyze_desc": "एआई तनाव जोखिम का विश्लेषण करता है",
    "improve": "3. सुधारें",
    "improve_desc": "तनाव कम करने के लिए सुझाव प्राप्त करें",
    "welcome_back": "वापसी पर स्वागत है",
    "signin_subtitle": "जारी रखने के लिए साइन इन करें",
    "email_address": "ईमेल पता",
    "email_placeholder": "john@example.com",
    "password": "पासवर्ड",
    "forgot_password": "पासवर्ड भूल गए?",
    "invalid_credentials": "अमान्य क्रेडेंशियल",
    "no_account": "क्या कोई खाता नहीं है? ",
    "signup": "साइन अप",
    "create_account": "खाता बनाएं",
    "signup_subtitle": "तनाव मुक्त यात्रा के लिए कॉर्टीसेंस से जुड़ें",
    "full_name": "पूरा नाम",
    "fullname_placeholder": "जॉन डो",
    "confirm_password": "पासवर्ड की पुष्टि करें",
    "password_length_tip": "कम से कम 8 अक्षर",
    "all_fields_required": "सभी फ़ील्ड आवश्यक हैं",
    "invalid_email": "कृपया एक वैध ईमेल दर्ज करें",
    "password_too_short": "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
    "passwords_do_not_match": "पासवर्ड मेल नहीं खाते",
    "reset_password": "पासवर्ड रीसेट करें",
    "reset_password_desc": "अपना ईमेल दर्ज करें और हम आपको एक लिंक भेजेंगे",
    "send_reset_link": "रीसेट लिंक भेजें",
    "back_to_signin": "साइन इन पर वापस जाएं",
    "daily_checkin": "दैनिक चेक-इन",
    "checkin_subtitle": "बेहतर जानकारी के लिए अपना दिन समझने में मदद करें",
    "analyze_stress": "तनाव का विश्लेषण करें",
    "processing_markers": "डेटा प्रोसेस हो रहा है...",
    "analyzing_heart_rate": "हृदय गति का विश्लेषण",
    "evaluating_sleep": "नींद का मूल्यांकन",
    "computing_stress": "तनाव की गणना",
    "generating_insights": "जानकारी उत्पन्न हो रही है",
    "analyzing_data_desc": "हमारा एआई आपके तनाव के स्तर का विश्लेषण कर रहा है",
    "checkin_complete_title": "चेक-इन पूरा हुआ",
    "checkin_complete_desc": "बहुत बढ़िया! आपने आज का चेक-इन पूरा कर लिया है।",
    "achievement_unlocked": "उपलब्धि प्राप्त की",
    "streak_7day": "आपने 7-दिन की स्ट्रीक पूरी की!",
    "weekly_improvement": "साप्ताहिक सुधार",
    "stress_drop_15": "इस सप्ताह आपके तनाव के स्तर में 15% की कमी आई है।",
    "high_stress_detected": "अधिक तनाव मिला",
    "high_stress_desc": "तनाव अधिक है। 5 मिनट का ब्रेक लें।",
    "avg_this_week": "इस सप्ताह औसत",
    "streak": "स्ट्रीक",
    "weekly_trend": "साप्ताहिक रुझान",
    "last_7_days": "पिछले 7 दिन",
    "low": "कम",
    "moderate": "मध्यम",
    "high": "अधिक",
    "stress_trends": "तनाव के रुझान",
    "overall_trend": "समग्र रुझान",
    "improving": "सुधार हो रहा है",
    "current_avg": "वर्तमान औसत",
    "monthly_progress": "मासिक प्रगति",
    "key_insight": "मुख्य जानकारी",
    "weekly_report": "साप्ताहिक रिपोर्ट",
    "avg_heart_rate": "औसत हृदय गति",
    "avg_sleep": "औसत नींद",
    "energy_level": "ऊर्जा स्तर",
    "best_day": "सबसे अच्छा दिन",
    "excellent": "उत्कृष्ट",
    "normal_range": "सामान्य श्रेणी",
    "history_log": "इतिहास",
    "stress_calendar": "तनाव कैलेंडर",
    "legend": "संकेत",
    "edit_profile": "प्रोफ़ाइल संपादित करें",
    "save_profile": "प्रोफ़ाइल सहेजें",
    "profile_updated": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई",
    "name_label": "नाम",
    "language_english": "English",
    "language_hindi": "हिन्दी (Hindi)",
    "language_telugu": "తెలుగు (Telugu)",
    "language_tamil": "தமிழ் (Tamil)",
    "language_french": "Français (French)",
    "chat_error": "कनेक्ट करने में समस्या हो रही है। कृपया पुनः प्रयास करें।",
    "chat_stress_reply": "आपके नवीनतम विश्लेषण के अनुसार, आपका तनाव %1$s है।",
    "chat_stress_high": "मैं कुछ श्वास व्यायाम की सलाह देता हूँ।",
    "chat_stress_low": "आप बहुत अच्छा कर रहे हैं!",
    "chat_sleep_reply": "आपकी औसत नींद %1$s है। बेहतर स्वास्थ्य के लिए 7-9 घंटे का लक्ष्य रखें।",
    "chat_hello": "नमस्ते! मैं आपका कॉर्टीसेंस असिस्टेंट हूँ। मैं आपकी कैसे मदद कर सकता हूँ?",
    "chat_default": "मुझे समझ आ गया। तनाव का प्रबंधन महत्वपूर्ण है।",
    "extracted_overview": "अवलोकन",
    "extracted_trends": "रुझान",
    "extracted_report": "रिपोर्ट",
    "extracted_monthly": "मासिक",
    "extracted_view_all": "सभी देखें",
    "extracted_heart_rate": "हृदय गति",
    "extracted_sleep": "नींद",
    "extracted_recent_check_ins": "हाल के चेक-इन",
    "extracted_bpm": "बीपीएम",
    "extracted_hrs": "घंटे",
    "extracted_ask_me_anything": "मुझसे कुछ भी पूछें",
    "extracted_ask_about_your_stres": "अपने तनाव के बारे में पूछें...",
    "extracted_cortisense": "कॉर्टीसेंस",
    "extracted_how_is_your_mood_rig": "अभी आपका मूड कैसा है?",
    "extracted_are_you_feeling_anxi": "क्या आप चिंतित महसूस कर रहे हैं?",
    "extracted_how_many_hours_did_y": "आप कितने घंटे सोए?",
    "extracted_how_much_caffeine_to": "आज कितनी कैफीन ली?",
    "extracted_screen_usage_today_": "आज स्क्रीन का उपयोग?",
    "extracted_how_busy_was_your_da": "आज आपका दिन कितना व्यस्त था?",
    "extracted_how_does_your_body_f": "आपका शरीर कैसा महसूस कर रहा है?",
    "extracted_good": "अच्छा",
    "extracted_okay": "ठीक",
    "extracted_bad": "बुरा",
    "extracted_very_fast": "बहुत तेज",
    "extracted_calm": "शांत",
    "extracted_fast": "तेज",
    "extracted_change_photo": "फोटो बदलें",
    "extracted_select_language": "भाषा चुनें",
    "extracted_cancel": "रद्द करें",
    "extracted_track_your_stress_pa": "समय के साथ अपने तनाव को ट्रैक करें",
    "extracted_recent_progress": "हाल की प्रगति",
    "extracted_current_week_summary": "इस सप्ताह का सारांश",
    "extracted_updated_from_your_la": "आपके नवीनतम रिकॉर्ड से अपडेट किया गया",
    "extracted_key_metrics": "मुख्य मेट्रिक्स",
    "extracted_breathing_exercise": "श्वास व्यायाम",
    "extracted_5_min": "5 मिनट",
    "extracted_stay_updated_on_your": "अपनी स्वास्थ्य यात्रा पर अपडेट रहें",
    "extracted_monthly_report": "मासिक रिपोर्ट",
    "extracted_overview_of_all_your": "आपके सभी डेटा का अवलोकन",
    "extracted_average_stress_score": "औसत तनाव स्कोर",
    "extracted_stress_distribution": "तनाव वितरण",
    "extracted_monthly_achievement": "मासिक उपलब्धि",
    "extracted_factor_breakdown": "कारक विवरण",
    "extracted_what_influences_your": "तनाव को क्या प्रभावित करता है",
    "extracted_contribution_analysi": "योगदान विश्लेषण",
    "extracted_ai_recommendation": "एआई सिफ़ारिश",
    "extracted_your_past_daily_entr": "आपकी पिछली दैनिक प्रविष्टियाँ",
    "extracted_color_coded_stress_v": "रंग-कोडित तनाव विज़ुअलाइज़ेशन",
    "extracted_current_month": "वर्तमान माह",
    "extracted_nutrition_tips": "पोषण संबंधी सुझाव",
    "extracted_eat_to_reduce_stress": "तनाव कम करने के लिए खाएं",
    "extracted_food_stress_connecti": "भोजन और तनाव का संबंध",
    "extracted_what_you_eat_directl": "आप जो खाते हैं वह आपके तनाव को सीधे प्रभावित करता है।",
    "extracted_eat_stress_reducing_": "तनाव कम करने वाले खाद्य पदार्थ खाएं",
    "extracted_limit_caffeine_intak": "कैफीन का सेवन सीमित करें",
    "extracted_mindfulness": "माइंडफुलनेस",
    "extracted_guided_meditation": "निर्देशित ध्यान",
    "extracted_start_your_session": "अपना सत्र शुरू करें",
    "extracted_find_a_quiet_place_a": "एक शांत जगह खोजें और आराम से बैठें",
    "extracted_duration": "अवधि",
    "extracted_guided_sessions": "निर्देशित सत्र",
    "extracted_morning_calm": "सुबह की शांति",
    "extracted_5_min_guided": "5 मिनट • निर्देशित",
    "extracted_great_job_today": "आज बहुत बढ़िया काम किया!",
    "extracted_you_ve_completed_you": "आपने अपना श्वास व्यायाम पूरा कर लिया है।",
    "extracted_view_my_progress": "मेरी प्रगति देखें",
    "extracted_back_to_home": "होम पर वापस जाएं",
    "extracted_10_points_earned": "+10 अंक अर्जित किए",
    "extracted_ai_assistant": "एआई सहायक",
    "extracted_type_a_message": "एक संदेश टाइप करें...",
    "extracted_history": "इतिहास",
    "extracted_score": "स्कोर",
    "extracted_date": "तारीख",
    "extracted_how_are_you_feeling_": "आप कैसा महसूस कर रहे हैं?",
    "extracted_let_s_log_your_daily": "आइए आपका दैनिक डेटा लॉग करें",
    "extracted_no_factors_logged": "कोई कारक लॉग नहीं किया गया",
    "extracted_excellent_job_keep_m": "बहुत बढ़िया काम! इसे जारी रखें।",
    "extracted_you_re_doing_well_bu": "आप अच्छा कर रहे हैं, लेकिन ध्यान दें।",
    "extracted_high_stress_detected": "अधिक तनाव! कृपया आराम करें।",
    "extracted_ai_analysis": "एआई विश्लेषण",
    "extracted_your_cortisol_indica": "आपके कोर्टिसोल संकेतक:",
    "extracted_you_haven_t_logged_a": "आपने अभी तक कोई डेटा लॉग नहीं किया है।",
    "extracted_check_in_now": "अभी चेक-इन करें"
}

tree = ET.parse('app/src/main/res/values-hi/strings.xml')
root = tree.getroot()

for child in root:
    if 'name' in child.attrib:
        key = child.attrib['name']
        if key in hi_dict:
            child.text = hi_dict[key]
            
xml_str = ET.tostring(root, encoding='utf-8', xml_declaration=True).decode('utf-8')
with open('app/src/main/res/values-hi/strings.xml', 'w', encoding='utf-8') as f:
    f.write(xml_str.replace('><', '>\n    <').replace('</resources>', '\n</resources>'))

print("Hindi translations applied.")
